const config = {
  API_KEY: process.env.REACT_APP_API_KEY,
  AUTH_DOMAIN: process.env.REACT_APP_AUTH_DOMAIN,
  PROJECT_ID: process.env.REACT_APP_PROJECT_ID,
  STORAGE_BUCKET: process.env.REACT_APP_STORAGE_BUCKET,
  MESSAGING_SENDER_ID: process.env.REACT_APP_MESSAGING_SENDER_ID,
  APP_ID: process.env.REACT_APP_APP_ID,
  CLOUDINARY_URL_UPLOAD: process.env.REACT_APP_CLOUDINARY_URL_UPLOAD || '',
  CLOUDINARY_UPLOAD_PRESET:
    process.env.REACT_APP_CLOUDINARY_UPLOAD_PRESET || '',
};

export default config;
