const variables = process.env;
const config = {
  API_KEY: variables.REACT_APP_API_KEY,
  AUTH_DOMAIN: variables.REACT_APP_AUTH_DOMAIN,
  PROJECT_ID: variables.REACT_APP_PROJECT_ID,
  STORAGE_BUCKET: variables.REACT_APP_STORAGE_BUCKET,
  MESSAGING_SENDER_ID: variables.REACT_APP_MESSAGING_SENDER_ID,
  APP_ID: variables.REACT_APP_APP_ID,
  CLOUDINARY_URL_UPLOAD: variables.REACT_APP_CLOUDINARY_URL_UPLOAD || '',
  CLOUDINARY_UPLOAD_PRESET: variables.REACT_APP_CLOUDINARY_UPLOAD_PRESET || '',
};

export default config;
